# Generated by Django 3.0.6 on 2020-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200521_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_picturename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
