# Generated by Django 3.0.6 on 2020-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_book_picturename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateField(default='', verbose_name='data published'),
        ),
    ]
